---
apiVersion: hco.kubevirt.io/v1alpha1
kind: HyperConverged
metadata:
  name: hyperconverged-cluster
spec:
  CDIImagePullPolicy: IfNotPresent
  KubeVirtImagePullPolicy: IfNotPresent
  KWebUIImagePullPolicy: IfNotPresent

