#!/bin/bash

KUBEVIRT_VERSION="v0.15.0"
CDI_VERSION="v1.6.0"
NETWORK_ADDONS_VERSION="v0.3.0"
KWEBUI_VERSION="v2.0.0-7"

CONTAINER_REGISTRY="docker.io/kubevirt"
#CONTAINER_REGISTRY="brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888"
